sudo: required
dist: trusty
language: scala

scala:
- 2.11.11
- 2.12.3

env:
- JDK=oraclejdk8 CB=4.1.1
- JDK=openjdk8 CB=4.1.1
- JDK=oraclejdk8 CB=4.5.0
- JDK=openjdk8 CB=4.5.0

before_install:
  - sudo wget http://packages.couchbase.com/releases/$CB/couchbase-server-enterprise_$CB-ubuntu14.04_amd64.deb
  - sudo dpkg -i couchbase-server-enterprise_$CB-ubuntu14.04_amd64.deb
  - sleep 20
# http://developer.couchbase.com/documentation/server/4.1/cli/cbcli-intro.html
  - /opt/couchbase/bin/couchbase-cli cluster-init -c 127.0.0.1:8091 --cluster-username=Administrator --cluster-password=password --cluster-ramsize=256
  - /opt/couchbase/bin/couchbase-cli bucket-create -c 127.0.0.1:8091 -u Administrator -p password --bucket=fodi --bucket-password=fodi_pw --bucket-type=couchbase --bucket-port=11211 --bucket-ramsize=100 --bucket-replica=0
#  - /opt/couchbase/bin/couchbase-cli bucket-delete -c 192.168.0.1:8091 -u Administrator -p password --bucket=default
  - /opt/couchbase/bin/couchbase-cli bucket-create -c 127.0.0.1:8091 -u Administrator -p password --bucket=acc --bucket-password=acc_pw --bucket-type=couchbase --bucket-port=11211 --bucket-ramsize=100 --bucket-replica=0

before_script:
  - jdk_switcher use $JDK

script:
  - sbt ++$TRAVIS_SCALA_VERSION test

cache:
  directories:
    - $HOME/.ivy2/cache/
    - $HOME/.sbt/boot/

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
